### CURRENT STAGE OF THIS DOCUMENT: Rapidly changing, highly incomplete, based on a four node configuration, though only three nodes are available at the time of this writing, likely brittle do to lots of automation based on this specific configuration.
#### Last updated: 2019.10.12, late PM PDT

#### Things to fix in this document:
* Need to link CaaSPv4 doc at the end
* Need to pull the nginx and some of the AutoYaST stuff out and put it into a separate doc that gets linked into this one
* Need to change the geeko user name to sles
* Need to change the order of the nodes from c -> a to a -> d
* Need to ensure three node to four node conversion (and be ready to easily support more than four nodes)

CAUTION: The described procedure outlined in this document leverages AutoYaST but does not include procedures for configuring DHCP (to avoid potential conflict with existing DHCP servers). For this reason all of the nodes must boot in Legacy mode, not UEFI or UEFI Secure Boot mode. This allows the "Boot Options" line to be used when booting the nodes from and ISO or DVD image. If the nodes cannot be booted in Legacy mode, the nodes will have to be manually configured correctly for the remainder of the procedure to be used. It is beyond the scope of this document to cover completing this procedure without AutoYaST.

#### This document is a strictly guided, step-by-step implementation of a specific configuration based on the SUSE Enterprise Storage 6 Deployment Guide: https://documentation.suse.com/ses/6/single-html/ses-deployment/#book-storage-deployment
* This specific configuration is based on five nodes:
** Administrative Workstation - VM or bare-metal host
** Four OSD Nodes - bare-metal hosts
** Three Monitors - collocated with the first three OSD Nodes
** One Rados (S3/Swift) Gateways (RGW) - collocated it the fourth OSD Node

#### Format of this document will be to create SES6 PoC installation notes here, then link https://github.com/alexarnoldy/caasp-ses-datahub/blob/master/caaspv4-installation-notes.adoc

IMPORTANT: All changes to the SES6 procedures will be made here. All changes to the CaaSP4v procedures will be made in the linked document.  

CAUTION: This guide can be used as a reference while deploying different configurations, but deviating from the specified design will cause unpredicable results

NOTE: Though the SES6 cluster will be used primarily to support the CaaS Platform cluster, it will be installed as a stand-alone storage cluster. This will allow it support additional services beyond the CaaS Platform cluster

.Required preparation that is not yet covered
* Establish an IP schema for the cluster. In this document, the Administrative Workstation (aka ses-admin.stable.suse.lab) is 172.16.200.130, the four OSD/Monitor/RGW nodes are 172.16.200.131-134
* Populate DNS records that are available to the cluster nodes

.Install the Administrative Workstation:
* Can be a VM, as long as it has access to the Internet and the cluster network
* 4 vCPU, 4096MB mem, 20GB qcow2 boot drive in default libvirt location
* Booting from ISO: Select "Installation" BUT DO NOT PRESS ENTER
* On "Boot Options:" line: `ifcfg=eth0=172.16.200.130/24,172.16.200.1,172.16.250.2,stable.suse.lab hostname=ses-admin.stable.suse.lab`
** Format of ifcfg=eth0 is <node IP address/cidr mask>,<default gateway>,<primary DNS server>,<search domain>
* Press Enter

IMPORTANT: Use the both the SLES 15 SP1 and SUSE Enterprise Storage 6 subscription keys to register all SES nodes, including the Administrative Workstation

* Use the SLES 15 SP1 subscription key first, as with a normal SUSE Linux Enterprise Server installation
* Enable the SUSE Enterprise Storage 6 and Containers Modules
** This should also enable the Basesystem Module 
* Provide the SUSE Enterprise Storage 6 subscription key
* Select the "Text Mode" System Role 

////
IMPORTANT: Use great care in selecting the system (boot) drive to ensure an OSD drive or write-caching drive isn't inadvertently used as the system drive. If this occurs, the node will need to be re-installed. If this error is propogated into the AutoYaST file that is used to install the remaining OSD nodes, all affect nodes will need to be re-installed.
////

* Select any partitioning scheme, but take the following into consideration:
** It is NOT RECOMMENDED to enable LVM 

IMPORTANT: LVM is not needed on SES cluster nodes and is incompatible with OSD drives. For that reason it is often safer to avoid LVM on all SES cluster nodes

** It is highly recommended to deselect "Enlarge to RAM Size for Suspend"
** A separate Home Partition is not needed on the OSD Nodes but can be configured, if desired
* Create New User:
** User's Full Name and Username: geeko

IMPORTANT: It is recommended to use a secure password that will work with all elements of the PoC environment. Therefore a password should be selected that includes at least one upper case and one lower case letter, one number and at least one of the following three special characters: ! # $

* Select "Use this password for system administrator", but do not select Automatic Login 
* On the final "Installation Settings" screen:
** Under Security, disable the Firewall
* Install

.Finish preparing the Management workstation:
* `sudo bash -c "echo 'geeko ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers.d/01geeko"`
* `ssh-keygen`
* `cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys`
** This is the eaisest way to insert the Management Workstation's SSH key into the AutoYaST clone file
* `sudo yast timezone`
** `other Settings`
** `Synchronize with NTP server`
** `Synchronize now`
** `Run NTP as daemon`
** `Save NTP Configuration`
** `Accept`, then `OK`

.Create an AutoYaST clone file of the Management Workstation
** `sudo yast2 clone_system`
*** Approve the installation of the AutoYaST2 package
** `mkdir autoyast_templates`
** `sudo mv /root/autoinst.xml ~/autoyast_templates/ses-osd-c.xml`
** `sudo chmod -R 777 ~/autoyast_templates/`

** Setup Docker and the nginx webserver
*** `sudo zypper -n in docker`
*** `sudo systemctl start docker.service && sudo systemctl enable docker.service`
*** `sudo usermod -aG docker geeko ; sudo su - geeko`
*** Launch nginx container: `docker run --name autoyast-nginx -v /home/geeko/autoyast_templates:/usr/share/nginx/html:ro -P -d nginx:latest`
**** Note: This container will not automatically start after rebooting the Management Workstation. Use `docker start autoyast-nginx` to start it manually
*** Check the port used by the nginx container:
**** `docker ps`
**** The port will listed under PORTS, for example, port 32768 would be indicated with: `0.0.0.0:32768->80/tcp`
**** Set this variable to the nginx port: `NGINX_PORT=""`
*** Test that the master autoyast file is available: `curl http://ses-admin.stable.suse.lab:$NGINX_PORT/ses-osd-c.xml`
**** The output should be the entire ses-osd-c.xml file

.Update the ses-osd-c.xml AutoYaST file with the correct hostname and IP address
* `sudo zypper -n in xmlstarlet`
* `cd autoyast_templates/`
* Verify that getent returns the correct IP address and hostname. If not, DO NOT run the subsequent `xml ed` and `sed` commands
** `getent hosts ses-osd-c`
* Update hostname in the ses-osd-c.xml file: xml ed -L -u "//_:networking/_:dns/_:hostname" -v ses-osd-c ses-osd-c.xml
** Set this variable to the Administrative Workstation's IP address (i.e. 172.16.200.130): MANAGEMENTIP=""
** `OSDIP=`getent hosts ses-osd-c | awk '{print$1}'`; sed -i "s/$MANAGEMENTIP/$OSDIP/" ses-osd-c.xml`
* If the Administrative Workstation is a VM, run this command: xml ed -L -d "//_:services-manager/_:services/_:enable/_:service[text()='spice-vdagentd']"  ses-osd-c.xml

.Update the correct boot drive for the OSD Node

CAUTION: The following steps assume that you know the size of the OSD Node's boot drive, the boot drive is a different size than all other drives on the OSD, and that all OSD Nodes are configured exactly the same. Configurations outside of these parameters are beyond the scope of this document.

* Remove the specified /dev/vda or /dev/sda element from the AutoYaST file:
** If the SES6 Admin Node is a VM, run this command: `xml ed -L -d "//_:partitioning/_:drive/_:device[text()='/dev/vda']" ses-osd-c.xml`
** If the SES6 Admin Node is a bare-metal server, run this command: `xml ed -L -d "//_:partitioning/_:drive/_:device[text()='/dev/sda']" ses-osd-c.xml`
* Insert the minimum and maximum size search parameters for the boot drive:
** `cd ~/autoyast_templates/; vim master.xml`
** Add the following element right below:
  <partitioning config:type="list">
    <drive>
----
      <initialize config:type="boolean">true</initialize>
      <skip_list config:type="list">
        <listentry>
  	<!-- skip devices that are 100MB smaller or less than the desired boot drive -->
  	<skip_key>size_k</skip_key>
  	<skip_value>MINIMUM</skip_value>
  	<skip_if_less_than config:type="boolean">true</skip_if_less_than>
        </listentry>
        <listentry>
  	<!-- skip devices that are 100MB larger or more than the desired boot drive -->
  	<skip_key>size_k</skip_key>
  	<skip_value>MAXIMUM</skip_value>
  	<skip_if_more_than config:type="boolean">true</skip_if_more_than>
        </listentry>
      </skip_list>
----

** Update MINIMUM with a value that is about 100MB less, and MAXIMUM with a value that is about 100MB greater, than the size of the boot drive
*** Both MINIMUM and MAXIMUM must be expressed in KB
**** For example, for a boot drive that is 550GB, set MINIMUM to 471859200 and MAXIMUM to 681574400


* Add the following element at the top of the file, right below <profile ... >, update MY_EMAIL_ADDRESS with the correct email address, plus MY_SLES_REGCODE and MY_SES6_REGCODE, with your registration codes
----
  <suse_register>
    <do_registration config:type="boolean">true</do_registration>
    <email>MY_EMAIL_ADDRESS</email>
    <reg_code>MY_SLES_REGCODE</reg_code>
    <install_updates config:type="boolean">true</install_updates>
    <slp_discovery config:type="boolean">false</slp_discovery>
    <addons config:type="list">
      <addon>
        <!-- Basesystem Module -->
        <name>sle-module-basesystem</name>
        <version>15.1</version>
        <arch>x86_64</arch>
      </addon>
      <addon>
        <!-- Server Applications Module -->
        <!-- Depends on: Basesystem Module -->
        <name>sle-module-server-applications</name>
        <version>15.1</version>
        <arch>x86_64</arch>
      </addon>
      <addon>
        <!-- SUSE Enterprise Storage -->
        <!-- Depends on: Server Applications Module -->
        <name>ses</name>
        <version>6</version>
        <arch>x86_64</arch>
        <reg_code>MY_SES6_REGCODE</reg_code>
      </addon>
    </addons>
  </suse_register>
----

*** Create the /home/geeko/autoyast_post_updates.sh file
**** ` echo "echo 'geeko ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers.d/01geeko" > /home/geeko/autoyast_templates/autoyast_post_updates.sh `

*** Add the following element directly above the <services-manager> element:
*** In the URL below, change the port number 32768 to the port number of your nginx container

////
Need to consolidate this with the nginx server for the CaaS Platform nginx server. It is ses-admin.stable.suse.lab here and admin.caaspv4.com there
////

----
    <scripts>
      <post-scripts config:type="list">
        <script>
          <debug config:type="boolean">true</debug>
          <feedback config:type="boolean">false</feedback>
          <feedback_type/>
          <filename>autoyast_post_updates.sh</filename>
          <interpreter>shell</interpreter>
          <location><![CDATA[http://ses-admin.stable.suse.lab:32768/autoyast_post_updates.sh]]></location>
          <notification>Performing_Final_Updates</notification>
          <param-list config:type="list"/>
          <source><![CDATA[]]></source>
        </script>
      </post-scripts>
    </scripts>
----


.AutoYaST install the first OSD Node

CAUTION: The steps below assume eth0 has network access to the ses-admin node. If this is not the case, asjusted the "Boot Options" line below to specify a NIC on the OSD Node that has network access to the ses-admin node.

* Provide the SLES 15 SP1 DVD1 installer DVD or ISO to the VM or host BIOS
* Start the Master Node from DVD ISO,  Select "Installation" at DVD GRuB screen, but DO NOT PRESS ENTER
* On Boot Options line: `autoyast=http://ses-admin.stable.suse.lab:<nginx port>/ses-osd-c.xml ifcfg=eth0=<IP of ses-osd-c>/24,<IP of gateway>,<IP of DNS server>,stable.suse.lab hostname=ses-osd-c.stable.suse.lab`

.After OSD Node completes installation, Adjust its networking to suit the environment 
* Note: This document shows the procdure for creating a bonded network from eth0
    and eth1, then assigning the node's IP address to that bond 
** Your configuration may be different
* Perform the following steps from the OSD Node's console:

TIP: In yast, Tab will help you navigate through panes and options. Each option in yast will have a letter highlighted.
     Using "Alt" + that letter will directly open that option.

** sudo yast lan
** (Highlight eth0) -> Delete -> OK
** sudo yast lan
** Add -> Device Type -> Bond -> Next
** (Select Statically Assigned IP Address) -> IP Address -> (input the Master Node's IP address)
** (Adjust the Subnet Mask, if needed) -> Bonded Slaves -> Yes
** (Select both eth0 and eth1) -> Next
** Routing -> (Ensure the Device for Default IPv4 Gateway is -) -> OK
* Verify networking is functioning correctly:
** ip a
** ping opensuse.com



when you get to accepting salt keys, if all the host names aren't showing up as fully qualified, we need to look at it and remediate, as this will break stuff after the fact. 

also, there is a bug in SLES15SP1 where if you create a bond and assign the fqdn hostname to the interface that it will lose it after the first reboot. you have to go back into yast2 and re-declare it, and then it sticks.






// vim: set syntax=asciidoc:
