#### CURRENT STATE OF THIS DOCUMENT: Needs refining and clarification. Needs to show how to do this with `yast lan` as it's much easier and persistent

##### This doc shows how to allow VLAN tags to be passed up to the VM.
* This useful when software explicitly requires VLANs to function correctly, when testing a bare-metal design that relies on VLANs, and when addressing multiple VLANs from the VM, while only having host one bridge for network access

* One description I read says that if VLANs are specifed on the host, the tags will be stripped off, before the packet is directed to that VLAN virtual interface
* Host NIC cannot be in any bridges
** Need to test to see if a host IP can be applied to the bridge after it has been created
** Need to test to see if the bridge can be built on top of a bond

TIP: Run commands as root

`vi /etc/sysctl.conf`

* Add:
----
net.bridge.bridge-nf-call-ip6tables = 0
net.bridge.bridge-nf-call-iptables = 0
net.bridge.bridge-nf-call-arptables = 0
net.bridge.bridge-nf-filter-pppoe-tagged = 0
net.bridge.bridge-nf-filter-vlan-tagged = 0
----

`sysctl -p`

////
`zypper -n in bridge-utils`

* To get brctl

`zypper -n in net-tools-deprecated`

* To get ifconfig

`zypper -n in vlan`

* To get vconfig for configuring VLANs on the bridge
////

`zypper -n in bridge-utils net-tools-deprecated vlan`

* To get brctl, ifconfig, and vconfig; respectively

`grep 8021q /proc/modules`
* Use command `modprobe 8021q` to load the VLAN module, if it's not already loaded

`BRIDGE=br240`

`VLAN=241`

`HOST_INTERFACE=bond0`

`sudo brctl addbr $BRIDGE`

`sudo vconfig add $BRIDGE $VLAN`

`sudo ifconfig $BRIDGE up`

`sudo ip link set $BRIDGE.$VLAN up`

`sudo ifconfig $BRIDGE.$VLAN up`

`sudo brctl addif $BRIDGE $HOST_INTERFACE`

`sudo ifconfig $HOST_INTERFACE up`

* Use virt-manager to add a new network device with "Specify shared device name", then type `br240`

* When the VM boots up, it will have a single NIC, which is untagged to the native VLAN
** Use `yast lan` to add VLAN241 and assign an IP address

.Adding more VLANs to the bridge:

`BRIDGE=br240`

`VLAN=200`

`vconfig add $BRIDGE $VLAN`

`ifconfig $BRIDGE.$VLAN up`

////
This didn't work. Seems like wicked gets unstable when changes are made outside of yast
#### Creating VLANs and bridges without yast:

.NOTES
* `sudo ip link add link bond0 name vlan242 type vlan id 242`
* `sudo ip link add name br242 type bridge`
* `sudo ip link set vlan242 master br242`
* `sudo ip addr add 172.16.242.104/24 dev br242`
////




// vim: set syntax=asciidoc:
